/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fmqsdcgmnypsjnsvbtoa"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtcXNkY2dtbnlwc2puc3ZidG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODI0NjQsImV4cCI6MjA3NDA1ODQ2NH0.7Dxm7ecNe5ucFtxXRusaDIDOmdTmyUsgSWRcHweZQh4"

